# Generated by Django 5.1.4 on 2025-03-20 13:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.CharField(max_length=50)),
                ('team_1_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='club_emblem')),
                ('team_2', models.CharField(max_length=50)),
                ('team_2_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='club_emblem')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
