# Generated by Django 5.1.4 on 2025-03-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_match_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team_1_logo',
            new_name='team_1_emblem',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team_2_logo',
            new_name='team_2_emblem',
        ),
    ]
