# Generated by Django 5.1.4 on 2025-03-27 18:01

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_match_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayProgramData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(blank=True, max_length=50, null=True)),
                ('club_emblem', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='club_emblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_program', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
