# Generated by Django 5.1.4 on 2025-04-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_displayprogramdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayprogramdata',
            name='use_emblems',
            field=models.BooleanField(default=True),
        ),
    ]
