# Generated by Django 5.1.4 on 2024-12-18 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('monday_type', models.CharField(blank=True, choices=[('Тренировка', 'Тренировка'), ('Мач', 'Мач')], null=True)),
                ('monday_time', models.TimeField(blank=True, null=True)),
                ('monday_place', models.CharField(blank=True, null=True)),
                ('tuesday_type', models.CharField(blank=True, choices=[('Тренировка', 'Тренировка'), ('Мач', 'Мач')], null=True)),
                ('tuesday_time', models.TimeField(blank=True, null=True)),
                ('tuesday_place', models.CharField(blank=True, null=True)),
                ('wednesday_type', models.CharField(blank=True, choices=[('Тренировка', 'Тренировка'), ('Мач', 'Мач')], null=True)),
                ('wednesday_time', models.TimeField(blank=True, null=True)),
                ('wednesday_place', models.CharField(blank=True, null=True)),
                ('thursday_type', models.CharField(blank=True, choices=[('Тренировка', 'Тренировка'), ('Мач', 'Мач')], null=True)),
                ('thursday_time', models.TimeField(blank=True, null=True)),
                ('thursday_place', models.CharField(blank=True, null=True)),
                ('friday_type', models.CharField(blank=True, choices=[('Тренировка', 'Тренировка'), ('Мач', 'Мач')], null=True)),
                ('friday_time', models.TimeField(blank=True, null=True)),
                ('friday_place', models.CharField(blank=True, null=True)),
                ('saturday_type', models.CharField(blank=True, choices=[('Тренировка', 'Тренировка'), ('Мач', 'Мач')], null=True)),
                ('saturday_time', models.TimeField(blank=True, null=True)),
                ('saturday_place', models.CharField(blank=True, null=True)),
                ('sunday_type', models.CharField(blank=True, choices=[('Тренировка', 'Тренировка'), ('Мач', 'Мач')], null=True)),
                ('sunday_time', models.TimeField(blank=True, null=True)),
                ('sunday_place', models.CharField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
