# Generated by Django 5.1.4 on 2025-01-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='friday_type',
            field=models.CharField(blank=True, choices=[('training', 'Тренировка'), ('mach', 'Мач')], null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='monday_type',
            field=models.CharField(blank=True, choices=[('training', 'Тренировка'), ('mach', 'Мач')], null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='saturday_type',
            field=models.CharField(blank=True, choices=[('training', 'Тренировка'), ('mach', 'Мач')], null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='sunday_type',
            field=models.CharField(blank=True, choices=[('training', 'Тренировка'), ('mach', 'Мач')], null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='thursday_type',
            field=models.CharField(blank=True, choices=[('training', 'Тренировка'), ('mach', 'Мач')], null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='tuesday_type',
            field=models.CharField(blank=True, choices=[('training', 'Тренировка'), ('mach', 'Мач')], null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='wednesday_type',
            field=models.CharField(blank=True, choices=[('training', 'Тренировка'), ('mach', 'Мач')], null=True),
        ),
    ]
