# Generated by Django 5.1.4 on 2025-01-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_displayscheduledata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayscheduledata',
            name='month',
            field=models.CharField(blank=True, choices=[('Януари', 'Януари'), ('Февруари', 'Февруари'), ('Март', 'Март'), ('Април', 'Април'), ('Май', 'Май'), ('Юни', 'Юни'), ('Юли', 'Юли'), ('Август', 'Август'), ('Септември', 'Септември'), ('Октомври', 'Октомври'), ('Ноември', 'Ноември'), ('Декември', 'Декември')], null=True),
        ),
    ]
