# Generated by Django 5.1.4 on 2025-01-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_rename_generation_displayscheduledata_team_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayscheduledata',
            name='club',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
