# Generated by Django 5.1.4 on 2025-01-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_displayscheduledata_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayscheduledata',
            name='color',
            field=models.CharField(choices=[('blue', 'син'), ('yellow', 'жълт'), ('red', 'червен'), ('green', 'зелен')], default='blue', max_length=20),
        ),
    ]
