# Generated by Django 5.1.4 on 2025-01-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='generation',
            new_name='team_generation',
        ),
        migrations.AddField(
            model_name='profile',
            name='team_generation_choice',
            field=models.CharField(choices=[('Отбор', 'Отбор'), ('Набор', 'Набор'), ('Без да посочваш', 'Без да посочваш')], default=2008, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='license',
            field=models.CharField(blank=True, choices=[('Uefa PRO', 'Uefa PRO'), ('Uefa A', 'Uefa A'), ('Uefa B', 'Uefa B'), ('Uefa C', 'Uefa C'), ('Национален C', 'Национален C'), ('Grassroots D', 'Grassroots D'), ('Без лиценз', 'Без лиценз')], max_length=30, null=True),
        ),
    ]
